import React from 'react';
import { Link } from 'react-router-dom';
import { getLatestAssessment } from '../utils/storage';
import { calculateDecision } from '../logic/decisionEngine';
import { ScoreGauge, RiskBadge, DecisionCard, Explainer } from '../components/SharedUI';
import { WeatherOverview } from '../components/WeatherWidgets';
import { ArrowRight, Printer } from 'lucide-react';
import { alternateCrops } from '../data/crops';

export const Dashboard = () => {
  const assessment = getLatestAssessment();
  
  if (!assessment) {
    return (
      <div className="text-center py-20">
        <h2 className="text-3xl font-bold text-gray-800 mb-4">Crop Damaged by Flood?</h2>
        <p className="text-gray-600 max-w-lg mx-auto mb-8">AgriRecover helps you analyze field conditions and weather forecasts to decide whether to recover, monitor, or replant.</p>
        <Link to="/assessment" className="inline-flex items-center gap-2 bg-agri-700 text-white px-6 py-3 rounded-xl hover:bg-agri-800 font-bold transition-all">
          Start Assessment <ArrowRight className="w-5 h-5" />
        </Link>
      </div>
    );
  }

  const result = calculateDecision(assessment);

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center mb-6 no-print">
        <h1 className="text-2xl font-bold text-gray-900">Current Field Status</h1>
        <button onClick={() => window.print()} className="flex items-center gap-2 text-agri-700 hover:bg-agri-50 px-4 py-2 rounded-lg font-medium border border-agri-200">
          <Printer className="w-4 h-4" /> Print Report
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <DecisionCard result={result} />
        <ScoreGauge score={result.recoveryScore} />
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 flex flex-col justify-center items-start">
          <span className="text-sm text-gray-500 uppercase font-semibold mb-2">Overall Risk</span>
          <RiskBadge risk={result.riskScore} />
          <div className="mt-4 pt-4 border-t w-full">
            <p className="text-sm font-medium text-gray-700">Crop: {assessment.crop.name} ({assessment.crop.stage})</p>
            <p className="text-sm text-gray-500 mt-1">Location: {assessment.location.name}</p>
          </div>
        </div>
      </div>

      <WeatherOverview weather={assessment.weather} />

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Explainer explanation={result.explanation} />
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
          <h3 className="text-lg font-bold text-gray-800 mb-4">Recommended Actions</h3>
          <ul className="space-y-3">
            {result.actions.map((act, i) => (
              <li key={i} className="flex gap-3 text-sm text-gray-700 items-start">
                <span className="bg-agri-100 text-agri-700 w-6 h-6 rounded-full flex items-center justify-center font-bold shrink-0">{i+1}</span>
                <span className="mt-0.5">{act}</span>
              </li>
            ))}
          </ul>
          
          {result.decision === 'REPLANT' && (
            <div className="mt-6 pt-6 border-t border-gray-100">
              <h4 className="font-bold text-gray-800 mb-3">Suitable Alternate Crops</h4>
              <div className="space-y-2">
                {alternateCrops.map(c => (
                  <div key={c.name} className="flex justify-between items-center text-sm p-3 bg-gray-50 rounded-lg border border-gray-100">
                    <span className="font-medium text-gray-800">{c.name}</span>
                    <span className="text-gray-500 text-xs">{c.duration}</span>
                    <span className="text-agri-700 font-bold">{c.suitability}/100</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
      
      <div className="mt-8 text-center text-xs text-gray-400 print-only">
        This report provides rule-based decision support. Actual decisions depend on local field realities. Generated by AgriRecover.
      </div>
    </div>
  );
};