export const weather = { location:"Sehore, Madhya Pradesh", temp:28, feels:30, humidity:72, wind:14, rainChance:70, rain:18, uv:5, soil:"Adequate", forecast:[{day:"Today",temp:28,rain:18},{day:"Tue",temp:27,rain:32},{day:"Wed",temp:29,rain:12},{day:"Thu",temp:31,rain:4},{day:"Fri",temp:30,rain:8},{day:"Sat",temp:29,rain:20},{day:"Sun",temp:28,rain:16}] };
export const mandi = [{day:"Mon",price:4670},{day:"Tue",price:4710},{day:"Wed",price:4690},{day:"Thu",price:4760},{day:"Fri",price:4810},{day:"Today",price:4850}];
export const alerts = [{level:"HIGH",title:"Heavy rainfall risk",place:"Bhopal district",time:"Next 24 hours",crops:"Soybean, Maize",action:"Clear drainage channels and move harvested produce."},{level:"MODERATE",title:"Yellow mosaic watch",place:"Sehore district",time:"This week",crops:"Soybean",action:"Inspect leaf veins and report suspected disease early."},{level:"LOW",title:"Mandi opportunity",place:"Indore mandi",time:"Today",crops:"Soybean",action:"Prices are up 3.8%; compare local transport costs."}];
export const schemes = [
  {name:"PM-KISAN",benefit:"Income support for eligible farmer families.",docs:"Identity, land record and bank details may be needed.",url:"https://pmkisan.gov.in/",status:"Open official portal"},
  {name:"PM Fasal Bima Yojana",benefit:"Crop insurance support subject to enrolment and notified crops.",docs:"Policy details, crop and loss evidence may be needed.",url:"https://pmfby.gov.in/",status:"Open official portal"},
  {name:"Soil Health Card",benefit:"Soil testing and nutrient guidance.",docs:"Farm and soil sample details.",url:"https://soilhealth.dac.gov.in/",status:"Open official portal"},
  {name:"PM Krishi Sinchayee Yojana",benefit:"Support for efficient irrigation, subject to local implementation.",docs:"Land and irrigation details.",url:"https://pmksy.mowr.gov.in/",status:"Open official portal"}
];
export async function diagnosePlant(symptom:string) { await new Promise(r=>setTimeout(r,550)); return { name: symptom.toLowerCase().includes("yellow") ? "Yellow mosaic (possible)" : "Leaf spot (possible)", confidence:78, symptoms:"Yellow patches, uneven growth, or leaf markings", immediate:"Inspect 10 plants across the field and improve drainage.", organic:"Remove severely affected leaves; discuss biocontrol options with an expert.", chemical:"Use only a product approved locally and follow the label and expert advice." }; }
export function aiAnswer(q:string) { const x=q.toLowerCase(); if(x.includes("rain")||x.includes("weather")) return "Rain is likely in the next 24 hours around Sehore. Clear drainage and avoid unnecessary irrigation. This is general guidance based on demo weather data."; if(x.includes("yellow")||x.includes("disease")) return "Yellowing can follow waterlogging, nutrient stress, or yellow mosaic. Check drainage and the leaf-vein pattern before choosing a treatment. A qualified local expert can confirm diagnosis."; if(x.includes("scheme")||x.includes("insurance")) return "You may review PM-KISAN, PM Fasal Bima Yojana, and state assistance. Eligibility and documents vary—use the official portal or agriculture office to confirm."; return "For your soybean field in its vegetative stage, start with soil moisture and a leaf inspection. Tell me the crop, symptom, and when it started for more tailored general guidance."; }
